{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-common",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha02.aar",
          "url": "hilt-common-1.0.0-alpha02.aar",
          "size": 3402,
          "sha512": "ecd54d49a72b39b207f7d59a1a4474c937f210caa6ee7239dd4b6cee130a6835826e1f5d6d7e4a94c4df832415dc7f9de2f3f615032bfe5b627e04647f37aa3d",
          "sha256": "0eedcde858fbddb72e57dd6eb076adca1677016b522aa9f2eb71d97f6f87f347",
          "sha1": "4bdd336aa3ac03fd09d8f0e917e4fc86ab7f9be3",
          "md5": "5f9d16797a139c1b0295da949bb1758b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha02.aar",
          "url": "hilt-common-1.0.0-alpha02.aar",
          "size": 3402,
          "sha512": "ecd54d49a72b39b207f7d59a1a4474c937f210caa6ee7239dd4b6cee130a6835826e1f5d6d7e4a94c4df832415dc7f9de2f3f615032bfe5b627e04647f37aa3d",
          "sha256": "0eedcde858fbddb72e57dd6eb076adca1677016b522aa9f2eb71d97f6f87f347",
          "sha1": "4bdd336aa3ac03fd09d8f0e917e4fc86ab7f9be3",
          "md5": "5f9d16797a139c1b0295da949bb1758b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha02-sources.jar",
          "url": "hilt-common-1.0.0-alpha02-sources.jar",
          "size": 4103,
          "sha512": "587c17cef0033356ab84cfeb243a647ac64c07d2614fd3f4850181b9d0cd1c4f3b40245202c6f75475f9465b690c092e72e044a31cf5b528dda76b03c5915742",
          "sha256": "57e0468ccd9bf3dc3d3d29afc614d1c5636159a8a752ac7de9d8cd45cc190277",
          "sha1": "b998e5905c8d25f5e7015a72123cccd9ef678269",
          "md5": "17fbb63187f85190e4ef9787b67b7acf"
        }
      ]
    }
  ]
}
