{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.1.1.aar",
          "url": "paging-runtime-3.1.1.aar",
          "size": 77964,
          "sha512": "15c20b6ddb4d6808dc93e7eb6691d152408332cd3e16f9a93cd356a8b6ad6c5288668624559fd38b568e8189d72214173d6ad11920f2880ee62db70d1441453b",
          "sha256": "1c16aead77f95103465c642923084a96eb930dcc55524c275c96408c4609d775",
          "sha1": "4e25cf711e51cf3433ab36a8a936353c5f2e7bd4",
          "md5": "dde1fda10a8e3bd9633da0d1c220260b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.1.1.aar",
          "url": "paging-runtime-3.1.1.aar",
          "size": 77964,
          "sha512": "15c20b6ddb4d6808dc93e7eb6691d152408332cd3e16f9a93cd356a8b6ad6c5288668624559fd38b568e8189d72214173d6ad11920f2880ee62db70d1441453b",
          "sha256": "1c16aead77f95103465c642923084a96eb930dcc55524c275c96408c4609d775",
          "sha1": "4e25cf711e51cf3433ab36a8a936353c5f2e7bd4",
          "md5": "dde1fda10a8e3bd9633da0d1c220260b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-3.1.1-sources.jar",
          "url": "paging-runtime-3.1.1-sources.jar",
          "size": 36032,
          "sha512": "67d453f155bac4a27e85e265b26660e4e9485547241d161ee17303ea40c7a30be489b32c253c6f1a085a9b5c00ee2efca375e7fe27a821831852493e5fa70f93",
          "sha256": "476fae3dc04c786eebb5810e8db714f8d4c6281b2b865baab9d1e76ad0fa1e94",
          "sha1": "4379f9bd714b051dbd90fae003cd58905df25f59",
          "md5": "dd2614cbf24217cb22874bcf730b7071"
        }
      ]
    }
  ]
}
