{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-lifecycle-viewmodel",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha01.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha01.aar",
          "size": 9836,
          "sha512": "dd11d9099f46087e1ae88a348215c0583720285dc353c1e36b4ef478b87b7d4db2c8b3efe9a6b40a0cca35ef41dd56b655ce70aefbe8a5263ad08e7876b26ffc",
          "sha256": "5aeda705d920fbcb6088f9f2bd7090ded302df9ea5a3a385fbd23b83ff27b84e",
          "sha1": "d3725c7cf1d0ad36403bea66c7ec86e1f7361ff7",
          "md5": "2de9472ae5bfd209c9ebfd9a19311cfb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha01.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha01.aar",
          "size": 9836,
          "sha512": "dd11d9099f46087e1ae88a348215c0583720285dc353c1e36b4ef478b87b7d4db2c8b3efe9a6b40a0cca35ef41dd56b655ce70aefbe8a5263ad08e7876b26ffc",
          "sha256": "5aeda705d920fbcb6088f9f2bd7090ded302df9ea5a3a385fbd23b83ff27b84e",
          "sha1": "d3725c7cf1d0ad36403bea66c7ec86e1f7361ff7",
          "md5": "2de9472ae5bfd209c9ebfd9a19311cfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha01-sources.jar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha01-sources.jar",
          "size": 4035,
          "sha512": "a32849d256d1858e5ae8c98af6099c138a40679629f3b72f4344b8323bfda409beea6ebbe2f9300b35f29a6d9a2e43999d182882aa244fdf09bb488b8559f745",
          "sha256": "c6c512f6e0fc157735e0eed463a4f81d20f9ebbf9b0afb2f480ee47f761e3b1e",
          "sha1": "f302e7f6520ff15916cb9ba2e223ebe12d0709b1",
          "md5": "0d3b56938d4de949f1d43a468a5e3703"
        }
      ]
    }
  ]
}
