{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.0-alpha03.aar",
          "url": "room-runtime-2.4.0-alpha03.aar",
          "size": 137216,
          "sha512": "96aa1e412540d02209209fc7be923adc7c489e39b8084006302834c0a32938f8f9ccc2e676fe9631267a862a938397256d25f81cdcc7aaeb21420e9704679eb5",
          "sha256": "5733a052e8e816376f3e2fc75a1fab77289e9da7a479a504f6f97501086ff5fb",
          "sha1": "f4770a1ba917f3fd25b9b58c0382ab157672e695",
          "md5": "d7d759d763022dcb850e63665a970a15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.4.0-alpha03.aar",
          "url": "room-runtime-2.4.0-alpha03.aar",
          "size": 137216,
          "sha512": "96aa1e412540d02209209fc7be923adc7c489e39b8084006302834c0a32938f8f9ccc2e676fe9631267a862a938397256d25f81cdcc7aaeb21420e9704679eb5",
          "sha256": "5733a052e8e816376f3e2fc75a1fab77289e9da7a479a504f6f97501086ff5fb",
          "sha1": "f4770a1ba917f3fd25b9b58c0382ab157672e695",
          "md5": "d7d759d763022dcb850e63665a970a15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.4.0-alpha03-sources.jar",
          "url": "room-runtime-2.4.0-alpha03-sources.jar",
          "size": 93705,
          "sha512": "f72965ff03e5f858cabff6865e1f44830523de30675d5d9ea3b29f65c7d71103d6a473fb4bb00e234285c16cad9c3e3fb914f5b8c003da500cc543a6815a4c29",
          "sha256": "cb8e56bfb77c44bc006566129eb03ba773b42143b1af23cc61e1f40b3af91f71",
          "sha1": "ca150cc031f25c593e395b3e943e67b5a0c9862c",
          "md5": "8d684e4804c2540b72c03cf2ac13ee37"
        }
      ]
    }
  ]
}
