{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-common",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha01.aar",
          "url": "hilt-common-1.0.0-alpha01.aar",
          "size": 3402,
          "sha512": "aa0ff64cad89db536ea685237e9c6e067c2c4073565ddf29ec995802892faeaa2bcad0ac8be00a527f689a8d6b6a5e32ab8b53f73a7fecb75c988a7fdb2b2c50",
          "sha256": "ded7b6079616be0eb39f42c7d0043ac61ce52ec5314e40e57d64c656451ae006",
          "sha1": "4a0a8313203169e541f2e1fe567e070596740a61",
          "md5": "22d73f5d30e268d9d802cf0a6b8c162c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha01.aar",
          "url": "hilt-common-1.0.0-alpha01.aar",
          "size": 3402,
          "sha512": "aa0ff64cad89db536ea685237e9c6e067c2c4073565ddf29ec995802892faeaa2bcad0ac8be00a527f689a8d6b6a5e32ab8b53f73a7fecb75c988a7fdb2b2c50",
          "sha256": "ded7b6079616be0eb39f42c7d0043ac61ce52ec5314e40e57d64c656451ae006",
          "sha1": "4a0a8313203169e541f2e1fe567e070596740a61",
          "md5": "22d73f5d30e268d9d802cf0a6b8c162c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha01-sources.jar",
          "url": "hilt-common-1.0.0-alpha01-sources.jar",
          "size": 4114,
          "sha512": "627ffbb9581073d3ed2da3c352fc945bf014cb56d949cf367cba768dd7111bfc0b1db1ee0b0b27a39ff090ab32ae8de65a4d77511d54c5e32cb9446141187afd",
          "sha256": "117e6fa416daa48eeff8fceb3d8a7015d569419f8a57f874137976cfd5f063ab",
          "sha1": "f4082ada9d2757b46ef498594f0210eca6bb2141",
          "md5": "68a42e6bd3aac3878885aaa643fa84d1"
        }
      ]
    }
  ]
}
