{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.2.0-alpha01.aar",
          "url": "sqlite-framework-2.2.0-alpha01.aar",
          "size": 13232,
          "sha512": "0d55cb5bdf1a9e4a69f479dde4438e7de15d7e54384e07db8ea054ded123ace8a89a6b41f3e9e22850aa7ea5ae6774ea7e66367ec68b60c93b3d2cde799844b8",
          "sha256": "54c1e842d3f4a19c34fd8b8cafe7f62a116b260c1d401c4b6ecaf7b17d0a4a33",
          "sha1": "9d3332d6d292cb06eb58121ea6a1e1fe4a0b1671",
          "md5": "491f6491d41c83a80a151dd6f6c62687"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-2.2.0-alpha01.aar",
          "url": "sqlite-framework-2.2.0-alpha01.aar",
          "size": 13232,
          "sha512": "0d55cb5bdf1a9e4a69f479dde4438e7de15d7e54384e07db8ea054ded123ace8a89a6b41f3e9e22850aa7ea5ae6774ea7e66367ec68b60c93b3d2cde799844b8",
          "sha256": "54c1e842d3f4a19c34fd8b8cafe7f62a116b260c1d401c4b6ecaf7b17d0a4a33",
          "sha1": "9d3332d6d292cb06eb58121ea6a1e1fe4a0b1671",
          "md5": "491f6491d41c83a80a151dd6f6c62687"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-framework-2.2.0-alpha01-sources.jar",
          "url": "sqlite-framework-2.2.0-alpha01-sources.jar",
          "size": 8456,
          "sha512": "e5ca2b2f1a4dcafaac5a88eff6a18a7c067e3cb4b7659b3271a45b52a40da189be8f668991b23ece1e965103c93bc582e0b53a59a9ad0bc5264aa0577f5bc06b",
          "sha256": "11d87175808c1e4de14fcdd3b44ef37d95f242ba16836b136d88654be9d3f3c3",
          "sha1": "276e5b579e93de6c6d9474d33d0e622cd35bf9e7",
          "md5": "2ebd102b7e5757772869b2c07707e71c"
        }
      ]
    }
  ]
}
