{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-2.2.0-alpha01.aar",
          "url": "sqlite-2.2.0-alpha01.aar",
          "size": 16896,
          "sha512": "a798f74a39e65ce8fc4dd931817a9a793382b45e47cc8080481935cda92221831279b82caecaa9c26b55e7c51e8564dd87ae9442db5a837f179e381b6a9325f9",
          "sha256": "53a6a9e0b3c2617e8dc6d12eb6448aac343bce6d3f184a91ae2245a8510b068f",
          "sha1": "255ff1856aedab0b74a38fbdd7389eeb91d58cbc",
          "md5": "816c475e54a3b5926a3458e7ae0d647e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-2.2.0-alpha01.aar",
          "url": "sqlite-2.2.0-alpha01.aar",
          "size": 16896,
          "sha512": "a798f74a39e65ce8fc4dd931817a9a793382b45e47cc8080481935cda92221831279b82caecaa9c26b55e7c51e8564dd87ae9442db5a837f179e381b6a9325f9",
          "sha256": "53a6a9e0b3c2617e8dc6d12eb6448aac343bce6d3f184a91ae2245a8510b068f",
          "sha1": "255ff1856aedab0b74a38fbdd7389eeb91d58cbc",
          "md5": "816c475e54a3b5926a3458e7ae0d647e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-2.2.0-alpha01-sources.jar",
          "url": "sqlite-2.2.0-alpha01-sources.jar",
          "size": 21571,
          "sha512": "0b1d0e0554740bd089dd42bbbefcdc70b6b5d0109b8d91e6beb83eb5aba664f47c840b872c5731bf7ad77e18a2ebb886e7aee8ef2e27e58d1a0ed57fba5677e4",
          "sha256": "698047ba9b49b93ac4480a4eefff5c33a1656e9a3126f5b831b283116c91ea0b",
          "sha1": "0ce7f01320b8870fe21dc55996764c8349c146cb",
          "md5": "fe16fdc077bfb0318c35178cd01c2a36"
        }
      ]
    }
  ]
}
