{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.5.1/kotlinx-coroutines-core-1.5.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "57u7m67lxbd6rili56rwnq7eoy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.5.1.jar",
          "url": "kotlinx-coroutines-core-jvm-1.5.1.jar",
          "size": 1482828,
          "sha512": "6cc7901e5ef56b77a9e38f6721d29b490397f88cc61b9b551f98e07265a160b4371a1d5cde7e886007aed03228af170ffd98d912b76734d8e334c2011b7bff44",
          "sha256": "3ff82734ea5e9ba9ffd675c6abcc22a69f924be2486ecd79c280403fd4922e22",
          "sha1": "59d09c330d2977b39e1e4c0e3711fc903e1b46b0",
          "md5": "e1b6c24073e7ccf410249a8a534ca5ad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.5.1.jar",
          "url": "kotlinx-coroutines-core-jvm-1.5.1.jar",
          "size": 1482828,
          "sha512": "6cc7901e5ef56b77a9e38f6721d29b490397f88cc61b9b551f98e07265a160b4371a1d5cde7e886007aed03228af170ffd98d912b76734d8e334c2011b7bff44",
          "sha256": "3ff82734ea5e9ba9ffd675c6abcc22a69f924be2486ecd79c280403fd4922e22",
          "sha1": "59d09c330d2977b39e1e4c0e3711fc903e1b46b0",
          "md5": "e1b6c24073e7ccf410249a8a534ca5ad"
        }
      ]
    }
  ]
}
