{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-lifecycle-viewmodel",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7094152"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.31-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha03.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha03.aar",
          "size": 10922,
          "sha512": "efef2d360116adb09d2ba00ab3161883cbc1262d163cb5d95eed4a7a8d112e912720763e9d5b6568729f078ee6b24e03d695990f6ef132a462badcca2748e999",
          "sha256": "fcf585543023cbad2e313b43ddbac6b813fb68c8867ea978df682f717edd596a",
          "sha1": "9d1c2ec32f8a02f3d5d4842d1c61df2386f8bc76",
          "md5": "7888e73070f2d95a499fed5e638320d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.31-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha03.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha03.aar",
          "size": 10922,
          "sha512": "efef2d360116adb09d2ba00ab3161883cbc1262d163cb5d95eed4a7a8d112e912720763e9d5b6568729f078ee6b24e03d695990f6ef132a462badcca2748e999",
          "sha256": "fcf585543023cbad2e313b43ddbac6b813fb68c8867ea978df682f717edd596a",
          "sha1": "9d1c2ec32f8a02f3d5d4842d1c61df2386f8bc76",
          "md5": "7888e73070f2d95a499fed5e638320d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha03-sources.jar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha03-sources.jar",
          "size": 4356,
          "sha512": "30407aee4a7960aa2881bb8e263967542f683873e8047944bbd037de262210aaec96c2a1ecb0c385b62d62b43300ea2428874d9ec9996167bdbc52b4d0a2cc60",
          "sha256": "3c4ac069bd9d72e86cad08cf882d61906b918c9c1f0bd9d7ecf8cd5823703ca0",
          "sha1": "d8dd51db680722bcfe864627597f4891e01bddca",
          "md5": "dd0a000cef417678895cb95020a948b8"
        }
      ]
    }
  ]
}
