{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7550673"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.3.6.aar",
          "url": "fragment-testing-1.3.6.aar",
          "size": 41733,
          "sha512": "7df0e021d74c2f53636e526bdbc9e446c1ec0deeb464c06f1fb4915cbfd67652bd4351cd5a4409d4cdff2364b1ad070227f9199299da24b8ab5411ab6a67e115",
          "sha256": "33ca692ff22d73a9c042730bd1db682e0ebfa2ed1d708728999ec9eae47ae859",
          "sha1": "1f62067413c8eacfbbcda68480d0e5549653b919",
          "md5": "047a5e021f6d80b590200c691b7d7019"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.3.6.aar",
          "url": "fragment-testing-1.3.6.aar",
          "size": 41733,
          "sha512": "7df0e021d74c2f53636e526bdbc9e446c1ec0deeb464c06f1fb4915cbfd67652bd4351cd5a4409d4cdff2364b1ad070227f9199299da24b8ab5411ab6a67e115",
          "sha256": "33ca692ff22d73a9c042730bd1db682e0ebfa2ed1d708728999ec9eae47ae859",
          "sha1": "1f62067413c8eacfbbcda68480d0e5549653b919",
          "md5": "047a5e021f6d80b590200c691b7d7019"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-testing-1.3.6-sources.jar",
          "url": "fragment-testing-1.3.6-sources.jar",
          "size": 5141,
          "sha512": "ade89371a7ff16cc5cdd3aafafb347ced7f46e67d14961c4164d51ff191c32bea815e003b8afde8ef13c1b4b37cc38673a54c51811e2c3b44497142bc90d5d2c",
          "sha256": "1cb0da781ce6db253d45971f83394e52b05a74726b29a17c6320c33976cfcea9",
          "sha1": "24088a4ced6be6776dfb945c55a98418442ae3fd",
          "md5": "63f7c0f259d7df3faa1d34b2b17b75e9"
        }
      ]
    }
  ]
}
