{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "7.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.3.1.aar",
          "url": "viewbinding-7.3.1.aar",
          "size": 2228,
          "sha512": "48cddf3648bf106d987a1895d7caedf4de52ec9f21d44389c04ea9aeb8cf63dc1f236b6f82698409956ecc84624f9cd2f805395ecd2fbed3a1d92cc65c2bd2c2",
          "sha256": "fdb16459f0f3f15aeff264ba645c8f41173bd9dd3a398af2d97f323b08870363",
          "sha1": "2caf4bd216a94b0d98c89994d85439ac155612cd",
          "md5": "ef3975a12cfd46e7a21082d5adaef1f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-7.3.1.aar",
          "url": "viewbinding-7.3.1.aar",
          "size": 2228,
          "sha512": "48cddf3648bf106d987a1895d7caedf4de52ec9f21d44389c04ea9aeb8cf63dc1f236b6f82698409956ecc84624f9cd2f805395ecd2fbed3a1d92cc65c2bd2c2",
          "sha256": "fdb16459f0f3f15aeff264ba645c8f41173bd9dd3a398af2d97f323b08870363",
          "sha1": "2caf4bd216a94b0d98c89994d85439ac155612cd",
          "md5": "ef3975a12cfd46e7a21082d5adaef1f5"
        }
      ]
    }
  ]
}
