{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-compiler",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6558100"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hilt-compiler-1.0.0-alpha01.jar",
          "url": "hilt-compiler-1.0.0-alpha01.jar",
          "size": 43299,
          "sha512": "6bc47c20ad0a17591f342d468d51302515b2fc77ec8d72ca83c31589693429583ddb795fa10685555dbb17f5589fcddfc4091e277692b1ab50e6a646a43a9cfd",
          "sha256": "355b1eb0a301ccc0031fce20d5ecf686cc218dd6f3d07982ffcc330c929cd1f6",
          "sha1": "b57e4d80b64146864f0442ceee4d11ab66a4a7cb",
          "md5": "4c8a62c5d445c86e7b4260eeebacf1d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-compiler-1.0.0-alpha01.jar",
          "url": "hilt-compiler-1.0.0-alpha01.jar",
          "size": 43299,
          "sha512": "6bc47c20ad0a17591f342d468d51302515b2fc77ec8d72ca83c31589693429583ddb795fa10685555dbb17f5589fcddfc4091e277692b1ab50e6a646a43a9cfd",
          "sha256": "355b1eb0a301ccc0031fce20d5ecf686cc218dd6f3d07982ffcc330c929cd1f6",
          "sha1": "b57e4d80b64146864f0442ceee4d11ab66a4a7cb",
          "md5": "4c8a62c5d445c86e7b4260eeebacf1d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-compiler-1.0.0-alpha01-sources.jar",
          "url": "hilt-compiler-1.0.0-alpha01-sources.jar",
          "size": 16225,
          "sha512": "669e9e877a5c38efac1d5dd710ddcfee63c56c608937ca6f17db977c53bf437bd3eabef0d3093213435c2f404bac46b0f8b7e4526a5d15bed172e02c89c63c11",
          "sha256": "a5e3745103a388313a5cbc48f559304345eab6827879647f19fcac2ab7aae09f",
          "sha1": "8a4ab4661eae2e07fcaacaef6114310332c9312e",
          "md5": "e5b44f2a07b5820dfbb422792c5e7430"
        }
      ]
    }
  ]
}
