{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "m326ik3lhfesbmhjner5abi3ba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.7.2.jar",
          "url": "okhttp-4.7.2.jar",
          "size": 792699,
          "sha512": "28870e2a4818ccfb6941abcb799c5ba18b326035c5c558d69ab7cdf62c105118e1550a4125c78e7d1adf1485d09f36e160f73b2779d5a63857f6f745eabb11ab",
          "sha256": "6b64ca1d2069751242984537d5de2cbe627ae000430f5117c47d8cb3d272facd",
          "sha1": "c9acfd63537db1d7d21d98a7405e22449bb881d6",
          "md5": "3b06faa72d8f1727408ed21c868b629e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.7.2.jar",
          "url": "okhttp-4.7.2.jar",
          "size": 792699,
          "sha512": "28870e2a4818ccfb6941abcb799c5ba18b326035c5c558d69ab7cdf62c105118e1550a4125c78e7d1adf1485d09f36e160f73b2779d5a63857f6f745eabb11ab",
          "sha256": "6b64ca1d2069751242984537d5de2cbe627ae000430f5117c47d8cb3d272facd",
          "sha1": "c9acfd63537db1d7d21d98a7405e22449bb881d6",
          "md5": "3b06faa72d8f1727408ed21c868b629e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.7.2-javadoc.jar",
          "url": "okhttp-4.7.2-javadoc.jar",
          "size": 261,
          "sha512": "542c5133ddb5eaf01d50f304ab94a676efb9a5c81a6403d4a59a07a4398fd98a872187adf050fc013766e6ae135b66634addc25f77a21868d0c95ee0050566fd",
          "sha256": "daea5d4fbe521965fced59c40333d5f90025073b040566c4b1661ea98b9e177f",
          "sha1": "6cff2dfca2abf8f6a81492afdd2a6d2aa353bdb3",
          "md5": "f75b2dbb25704e5666af844b9a32844f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.7.2-sources.jar",
          "url": "okhttp-4.7.2-sources.jar",
          "size": 361688,
          "sha512": "f12a28c71a1f10ba1be0e813a3fd7e21c3df1651db3674904e78311855064921dcb5f5995969d113ddae310d36c8dc0b8daef7a1d23cc3e6e9d784a361249414",
          "sha256": "88348cf944f841a7a8f5f38960474592e0c1ed8a53349cabe05b22d255479772",
          "sha1": "c5c4b2e00cd8458c8430925231fa0444c4780579",
          "md5": "8a139a841a28cb14eeaeb0a0eba11128"
        }
      ]
    }
  ]
}
