{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime-ktx",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.1.aar",
          "url": "paging-runtime-ktx-3.1.1.aar",
          "size": 1735,
          "sha512": "1873e2a488d36a6cf11364eaa9fc81b696ead4bc950a2a40e955834f267612e84e8624df9ea2a6a25af7319c8784ba92fea800d0de4a2033a7e6257beb5d1074",
          "sha256": "620e580fe447969a833b8283f397803516ae5a48fa01ce24410a2d13329f3bc9",
          "sha1": "440c00235b8215b7c9c184ff97b3654941518e56",
          "md5": "f8c1d6f244fc900f13b0aa646ef17be4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.1.aar",
          "url": "paging-runtime-ktx-3.1.1.aar",
          "size": 1735,
          "sha512": "1873e2a488d36a6cf11364eaa9fc81b696ead4bc950a2a40e955834f267612e84e8624df9ea2a6a25af7319c8784ba92fea800d0de4a2033a7e6257beb5d1074",
          "sha256": "620e580fe447969a833b8283f397803516ae5a48fa01ce24410a2d13329f3bc9",
          "sha1": "440c00235b8215b7c9c184ff97b3654941518e56",
          "md5": "f8c1d6f244fc900f13b0aa646ef17be4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.1-sources.jar",
          "url": "paging-runtime-ktx-3.1.1-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
