{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7085123"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0.aar",
          "url": "work-runtime-ktx-2.5.0.aar",
          "size": 22989,
          "sha512": "3779876d2ff83ae9c31fbc7113fab244e8c8e251fd69a0be11b181b6d83d255225b451cff739f27914660ca2453215f4234948b5da275f3d3a1b37cbf33dc02a",
          "sha256": "64d0a096e7bcedaf551200ddc8bf3e753cc2ee9a5b1a61db1be4904c0a4b35a9",
          "sha1": "d9a52639dfa31215f62245db42289ef747cf171b",
          "md5": "a402722b379534df5999ae0a214f2543"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0.aar",
          "url": "work-runtime-ktx-2.5.0.aar",
          "size": 22989,
          "sha512": "3779876d2ff83ae9c31fbc7113fab244e8c8e251fd69a0be11b181b6d83d255225b451cff739f27914660ca2453215f4234948b5da275f3d3a1b37cbf33dc02a",
          "sha256": "64d0a096e7bcedaf551200ddc8bf3e753cc2ee9a5b1a61db1be4904c0a4b35a9",
          "sha1": "d9a52639dfa31215f62245db42289ef747cf171b",
          "md5": "a402722b379534df5999ae0a214f2543"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0-sources.jar",
          "url": "work-runtime-ktx-2.5.0-sources.jar",
          "size": 7266,
          "sha512": "a0ab5bd09b7784913b99af8268edc6d94d530abb4460a9c0d57656de2bae03586161bfca31058dc888da13ec8a0e90780440f6726b4d0974c12c31ae59310657",
          "sha256": "f38861f7f1f461e8da880c5a02094e271770ebcb65e384794416ef6c5d65c31b",
          "sha1": "2fabc8c05c62815e39f1c863afd6893d5d5ef261",
          "md5": "72e1664de11d6c82c5682cd98702573e"
        }
      ]
    }
  ]
}
