{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.0-alpha03.jar",
          "url": "room-compiler-processing-2.4.0-alpha03.jar",
          "size": 716199,
          "sha512": "1f6ee21d3cd2edcdcf4a801a69ffeb7d27a66551fce32e5a6f8a9f8da8c50e76995d9b8c60ba0239c4394a855d667bcd5a5bcd892f9ecb7a37388990eaec4141",
          "sha256": "80dde48d8353a488aab0966a18be17d52bb016533394c6d2d01238464860bd4a",
          "sha1": "6ccfd34c2f566a7d57e41e612c0eab9f65a8c76c",
          "md5": "c5749661f03abfdd4634cc5615f35b40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.10-1.0.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.0-alpha03.jar",
          "url": "room-compiler-processing-2.4.0-alpha03.jar",
          "size": 716199,
          "sha512": "1f6ee21d3cd2edcdcf4a801a69ffeb7d27a66551fce32e5a6f8a9f8da8c50e76995d9b8c60ba0239c4394a855d667bcd5a5bcd892f9ecb7a37388990eaec4141",
          "sha256": "80dde48d8353a488aab0966a18be17d52bb016533394c6d2d01238464860bd4a",
          "sha1": "6ccfd34c2f566a7d57e41e612c0eab9f65a8c76c",
          "md5": "c5749661f03abfdd4634cc5615f35b40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.4.0-alpha03-sources.jar",
          "url": "room-compiler-processing-2.4.0-alpha03-sources.jar",
          "size": 153372,
          "sha512": "8855a9bad96e9df4adea01bf54196f564353bcb7ba226108d809752366036fbcad85d12cdded6ff21c033ca771437ab8d63782afad286a509e6895cf368ec49b",
          "sha256": "1fe0d6666ca63334abcd3d4d866d4ba4bf0a120b00942f611123656ddce93474",
          "sha1": "810eab129440d1323c873a0f8de1a079399a3155",
          "md5": "9325d39e3c47cb90bb24844436192716"
        }
      ]
    }
  ]
}
