{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-lifecycle-viewmodel",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6684396"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha02.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha02.aar",
          "size": 9967,
          "sha512": "c15a10114bbf3a6ae0e60c4ec269abc3127814c59babc8c41095be7422c502789145162a27ddfde9b52fbb0cf4741c54d6658a7e92db1e584eedb67175f6d8ca",
          "sha256": "5933ac351e81b51dc3c6af7d96c7284cf248ea14b995c4fa17040c7b9a0b57f9",
          "sha1": "8bc291baeeb1663eb2e53a2fcd39752eeff23900",
          "md5": "5a60207eb7f75f3b088f2eb4dc169883"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.28-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha02.aar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha02.aar",
          "size": 9967,
          "sha512": "c15a10114bbf3a6ae0e60c4ec269abc3127814c59babc8c41095be7422c502789145162a27ddfde9b52fbb0cf4741c54d6658a7e92db1e584eedb67175f6d8ca",
          "sha256": "5933ac351e81b51dc3c6af7d96c7284cf248ea14b995c4fa17040c7b9a0b57f9",
          "sha1": "8bc291baeeb1663eb2e53a2fcd39752eeff23900",
          "md5": "5a60207eb7f75f3b088f2eb4dc169883"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-1.0.0-alpha02-sources.jar",
          "url": "hilt-lifecycle-viewmodel-1.0.0-alpha02-sources.jar",
          "size": 4211,
          "sha512": "e7527a6fd037e3631678b3b23119815eabf4edccd7309f8aeedd443c37cd7a7f05237d31a53e1b6e9d6d15ffaf8b5f8738fcba38d8e93d650cbaa4fb3d9491b9",
          "sha256": "27079676c678f873a1842a595290c7e1014d71703eaa23fc37be52908406378c",
          "sha1": "d97cb84b8f4956837798987a55dc303bf6f6bf32",
          "md5": "b0cf767352760a62ec8f02cfbb5da7bb"
        }
      ]
    }
  ]
}
