{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0-alpha03.jar",
          "url": "room-compiler-2.4.0-alpha03.jar",
          "size": 3628675,
          "sha512": "0c0d666cc6c5c7a860b5d8cd233345a1d3f849298c315a73ba9fa53fda63c28968fc62c6776445cbcb75e9e9aaa4b074debcca0a3a376d3ed5d29f05175c5cfb",
          "sha256": "1dc2ca07b017b65ce6066a9dafc838b0946960ecf8a88495834b229e4dc1c127",
          "sha1": "345d22bc37c7b49020dd0902aa00bc31df862f71",
          "md5": "1a7ca9c2a9121c628952ce62b2f3ec22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.10-1.0.0-beta01"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.34.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.4.0-alpha03.jar",
          "url": "room-compiler-2.4.0-alpha03.jar",
          "size": 3628675,
          "sha512": "0c0d666cc6c5c7a860b5d8cd233345a1d3f849298c315a73ba9fa53fda63c28968fc62c6776445cbcb75e9e9aaa4b074debcca0a3a376d3ed5d29f05175c5cfb",
          "sha256": "1dc2ca07b017b65ce6066a9dafc838b0946960ecf8a88495834b229e4dc1c127",
          "sha1": "345d22bc37c7b49020dd0902aa00bc31df862f71",
          "md5": "1a7ca9c2a9121c628952ce62b2f3ec22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0-alpha03-sources.jar",
          "url": "room-compiler-2.4.0-alpha03-sources.jar",
          "size": 418390,
          "sha512": "468a7ffb78920a519fa61c1b3b66426b8162ad1971c7f98993dece56284a4cdcdcda803838e9cfcb56e3ed76d6e334642436cf0cf4719970c6ef36a426c56577",
          "sha256": "5b632457941caa388008a4302e9d07259d4e45256196a03c786663f1c355e792",
          "sha1": "b118d2d44becd7a19fd2ded9f59d0a61aa3e6e1a",
          "md5": "0e657b96d8a8763381144ace24e2d88e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.4.0-alpha03.jar",
          "url": "room-compiler-2.4.0-alpha03.jar",
          "size": 3628675,
          "sha512": "0c0d666cc6c5c7a860b5d8cd233345a1d3f849298c315a73ba9fa53fda63c28968fc62c6776445cbcb75e9e9aaa4b074debcca0a3a376d3ed5d29f05175c5cfb",
          "sha256": "1dc2ca07b017b65ce6066a9dafc838b0946960ecf8a88495834b229e4dc1c127",
          "sha1": "345d22bc37c7b49020dd0902aa00bc31df862f71",
          "md5": "1a7ca9c2a9121c628952ce62b2f3ec22"
        }
      ]
    }
  ]
}
