{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "room-migration-2.4.0-alpha03.jar",
          "url": "room-migration-2.4.0-alpha03.jar",
          "size": 22451,
          "sha512": "31e5497043c98d5b6e8709a5e37730fb6303ff8268b656b908c235dd74b966698ae59f5ee272d83f9c437f5ab3b38fb4c28e33b8f5c238017d0fb5448419395e",
          "sha256": "c5b4a79690d790b02a0e63dab05cb2dab91d5380eaccebcadb2f26247e34cff7",
          "sha1": "a7ba7ccea92805032e7f3631c366ddff91c83737",
          "md5": "fd0c41db0846bda554da53cba764debf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-migration-2.4.0-alpha03.jar",
          "url": "room-migration-2.4.0-alpha03.jar",
          "size": 22451,
          "sha512": "31e5497043c98d5b6e8709a5e37730fb6303ff8268b656b908c235dd74b966698ae59f5ee272d83f9c437f5ab3b38fb4c28e33b8f5c238017d0fb5448419395e",
          "sha256": "c5b4a79690d790b02a0e63dab05cb2dab91d5380eaccebcadb2f26247e34cff7",
          "sha1": "a7ba7ccea92805032e7f3631c366ddff91c83737",
          "md5": "fd0c41db0846bda554da53cba764debf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-migration-2.4.0-alpha03-sources.jar",
          "url": "room-migration-2.4.0-alpha03-sources.jar",
          "size": 17664,
          "sha512": "6c4955695f0103ecfe249d12f522021136814623113c783b2ac689d1f8343563917d013029d2303b4d0c0c0117d471c85a34a7869bfb792cc23992140faade5d",
          "sha256": "a217f028520ac7a91d5056c005128faf785af754a3ec326fae3563d0a5290a33",
          "sha1": "b7e745961e596dca1e3b8ee89e4158ffc90217e2",
          "md5": "0685ef47003dd9e05a7794753eecb7da"
        }
      ]
    }
  ]
}
