{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.4.0-alpha03.jar",
          "url": "room-common-2.4.0-alpha03.jar",
          "size": 22234,
          "sha512": "fb716ea504d230284944e2ab697fb6f35d59caff7aa79ef7e5e51cdebe076642912bf6aa2a173f86a4b5372da971bf2b506335fa3f529652060d4dbb82528b02",
          "sha256": "8c2abf655a985b44050822bf801896ce2a398b91b69651f7887ad2a5a136b51c",
          "sha1": "cae14e25bc64587b588f8346858273c6484056af",
          "md5": "f5ae8dccfa4ad319aa11d2a55e7aa995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.4.0-alpha03.jar",
          "url": "room-common-2.4.0-alpha03.jar",
          "size": 22234,
          "sha512": "fb716ea504d230284944e2ab697fb6f35d59caff7aa79ef7e5e51cdebe076642912bf6aa2a173f86a4b5372da971bf2b506335fa3f529652060d4dbb82528b02",
          "sha256": "8c2abf655a985b44050822bf801896ce2a398b91b69651f7887ad2a5a136b51c",
          "sha1": "cae14e25bc64587b588f8346858273c6484056af",
          "md5": "f5ae8dccfa4ad319aa11d2a55e7aa995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-common-2.4.0-alpha03-sources.jar",
          "url": "room-common-2.4.0-alpha03-sources.jar",
          "size": 53339,
          "sha512": "66a950ae5866b79217959c2d7b21ecf99d11c4750dbe766680d5edc4d94cd75d63b138ac61bac2c22f49a089c9e441bc2db30364de38a58c4c921de42dedf7f0",
          "sha256": "f571f142a84311b69b351f0d516aa8dadcd211a2eb7cbb6bb9ee9dffc346727e",
          "sha1": "05675792064c75bd33e21c5b814adff6ac663f47",
          "md5": "1c08c4c3c09cf9e33a162c4f2e0ec4ce"
        }
      ]
    }
  ]
}
