{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.0-alpha03.aar",
          "url": "room-ktx-2.4.0-alpha03.aar",
          "size": 35262,
          "sha512": "b992c170791c1128263c6b07db26d77309b448c0f24ea2a3a86b33e3691494280f0621c3609d60dd628fdb525680241adea3eaee212ef8a8d9dd9780444030f9",
          "sha256": "501bfbac4548f270d7a87d26f9d940aeffd11253539590354058c3ab9c2e99b8",
          "sha1": "4decae22125600ddb1c90dcb865c2c9113dfac18",
          "md5": "4db90508d5cb7936bbe67add8e1d7a26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.4.0-alpha03.aar",
          "url": "room-ktx-2.4.0-alpha03.aar",
          "size": 35262,
          "sha512": "b992c170791c1128263c6b07db26d77309b448c0f24ea2a3a86b33e3691494280f0621c3609d60dd628fdb525680241adea3eaee212ef8a8d9dd9780444030f9",
          "sha256": "501bfbac4548f270d7a87d26f9d940aeffd11253539590354058c3ab9c2e99b8",
          "sha1": "4decae22125600ddb1c90dcb865c2c9113dfac18",
          "md5": "4db90508d5cb7936bbe67add8e1d7a26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-ktx-2.4.0-alpha03-sources.jar",
          "url": "room-ktx-2.4.0-alpha03-sources.jar",
          "size": 6156,
          "sha512": "603e33e956062d904193ac77789eef86bdd35f69535b02d23b4ceab9031d88d8961abdda9b5a47db8e5996c785def4fc81204190c4dab14a2b507f98eaef02ec",
          "sha256": "ad74772915759a007b7eb74c5cd6c8274170dea2c4f55540eb51d3b9d3e9b825",
          "sha1": "9474824d8d29f2a28e480e388023c62155b57644",
          "md5": "a8c31d870d07acca17d63ce1d3921c76"
        }
      ]
    }
  ]
}
